language: bash
sudo: false
os:
  - linux
  - osx
matrix:
  - fast_finish: true
addons:
  apt:
    packages:
      - shellcheck
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install shellcheck; fi
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
script:
  - shellcheck bin/*
  - asdf plugin-test conduit https://github.com/gmcabrita/asdf-conduit.git
