language: bash
sudo: false
os:
  - linux
matrix:
  - fast_finish: true
addons:
  apt:
    packages:
      - shellcheck
before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
script:
  - shellcheck bin/*
  - asdf plugin-test conduit https://github.com/gmcabrita/asdf-conduit.git
