language: bash
sudo: false
os:
  - linux
  - osx
matrix:
  - fast_finish: true
install:
  # Install a custom version of shellcheck instead of Travis CI's default
  - scversion="stable"
  - wget "https://storage.googleapis.com/shellcheck/shellcheck-$scversion.linux.x86_64.tar.xz"
  - tar --xz -xvf "shellcheck-$scversion.linux.x86_64.tar.xz"
  - shellcheck() { "shellcheck-$scversion/shellcheck" "$@"; }
  - shellcheck --version
script:
  - shellcheck *.sh
before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
script:
  - shellcheck bin/*
  - asdf plugin-test conduit https://github.com/gmcabrita/asdf-conduit.git
